/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uf6projecte;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static uf6projecte.UF6Projecte.BD_NAME;
import static uf6projecte.UF6Projecte.PORT;
import static uf6projecte.UF6Projecte.PWD;
import static uf6projecte.UF6Projecte.URL;
import static uf6projecte.UF6Projecte.USER;

/**
 *
 * @author ausias
 */
public class VentanaGrups extends javax.swing.JFrame {

    private static int contadorGrups = 0;
    private static GrupTable grupTab;
    private static ArrayList<GrupEntity> llista_Grups;

    
    public VentanaGrups() {

        try {
            grupTab = new GrupTable();
            BDConnection bdCon = new BDConnection(URL, PORT, BD_NAME, USER, PWD);
            grupTab.setConnection(bdCon);
            VentanaGrups.llista_Grups = grupTab.GetAll();

        } catch (NullConnectionException | SQLException | ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        setResizable(false);
        initComponents();
    }

    public static GrupEntity getGrupActual() {
        return llista_Grups.get(contadorGrups);
    }
    private static int confirmarOperacio() {
        int result = 0;
        String[] options = {"Si", "No"};
        int opcio = JOptionPane.showOptionDialog(
                null,
                "Estàs segur de realitzar la operació?",
                "Comfirmació",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //no custom icon
                options, //button titles
                options[0] //default button
        );
        if (opcio == JOptionPane.YES_OPTION) {
            result = 0;
        } else if (opcio == JOptionPane.NO_OPTION) {
            result = 1;
        } else {
            result = 2;
        }
        return opcio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botoObrirAlumnes = new javax.swing.JButton();
        IDGrup = new javax.swing.JLabel();
        nomGr = new javax.swing.JLabel();
        numAlumnes = new javax.swing.JLabel();
        quotaGrup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botoSeguent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botoAnterior = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modificarGrup = new javax.swing.JButton();
        afegirGrup = new javax.swing.JButton();
        esborrarGrup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Grups");

        botoObrirAlumnes.setText("Editar Alumnes");
        botoObrirAlumnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoObrirAlumnesActionPerformed(evt);
            }
        });

        IDGrup.setText(Integer.toString(llista_Grups.get(contadorGrups).getID()));

        nomGr.setText(llista_Grups.get(contadorGrups).getNom());

        numAlumnes.setText(Integer.toString(llista_Grups.get(contadorGrups).getnumAlumnes()));

        quotaGrup.setText(Float.toString(llista_Grups.get(contadorGrups).getQuota()));

        jLabel2.setText("Codi Grup:");

        botoSeguent.setText("Següent Grup");
        botoSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSeguentActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom: ");

        botoAnterior.setText("Anterior Grup");
        botoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAnteriorActionPerformed(evt);
            }
        });

        jLabel4.setText("Nº Alumnes:");

        jLabel5.setText("Quota");

        modificarGrup.setText("Modificar");
        modificarGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarGrupActionPerformed(evt);
            }
        });

        afegirGrup.setText("Afegir");
        afegirGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirGrupActionPerformed(evt);
            }
        });

        esborrarGrup.setText("Esborrar");
        esborrarGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esborrarGrupActionPerformed(evt);
            }
        });

        jButton1.setText("Actualitzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Alumnes del Grup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botoObrirAlumnes)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botoAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botoSeguent)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(afegirGrup)
                        .addGap(18, 18, 18)
                        .addComponent(modificarGrup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(esborrarGrup)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quotaGrup)
                                    .addComponent(nomGr)
                                    .addComponent(numAlumnes)
                                    .addComponent(IDGrup))))
                        .addGap(96, 96, 96)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IDGrup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomGr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numAlumnes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quotaGrup))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afegirGrup)
                    .addComponent(esborrarGrup)
                    .addComponent(modificarGrup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoSeguent)
                    .addComponent(botoAnterior)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(botoObrirAlumnes))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoObrirAlumnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoObrirAlumnesActionPerformed
        try{
            if(!VentanaAlumnes.isOpenAlumnes){
                VentanaAlumnes ventana = new VentanaAlumnes();
                ventana.setVisible(true);
                ventana.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            } 
        } catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "No hi ha cap alumne creat, s'ha de inserir un directament",
                    "ERROR", JOptionPane.INFORMATION_MESSAGE);
            AfegirAlumne afegirAl = new AfegirAlumne();
            afegirAl.setVisible(true);
            afegirAl.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            VentanaAlumnes.isOpenAlumnes = false;
        }
        
    }//GEN-LAST:event_botoObrirAlumnesActionPerformed

    private void botoSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSeguentActionPerformed
        if (contadorGrups >= llista_Grups.size() - 1) {
            JOptionPane.showMessageDialog(null, "No hi ha grups posteriors a aquest",
                    "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ++contadorGrups;
            actualitzarMostrar();
        }

    }//GEN-LAST:event_botoSeguentActionPerformed

    private void botoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAnteriorActionPerformed
        if (contadorGrups == 0) {
            JOptionPane.showMessageDialog(null, "No hi ha grups anteriors a aquest",
                    "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            --contadorGrups;
            actualitzarMostrar();
        }
    }//GEN-LAST:event_botoAnteriorActionPerformed

    private void modificarGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarGrupActionPerformed
        if (!ModificarGrups.isOpen) {
            ModificarGrups modGr = new ModificarGrups();
            modGr.setVisible(true);
            modGr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_modificarGrupActionPerformed

    private void afegirGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirGrupActionPerformed
        if (!AfegirGrups.isOpenAfegirGrups) {
            AfegirGrups afegirGr = new AfegirGrups();
            afegirGr.setVisible(true);
            afegirGr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

    }//GEN-LAST:event_afegirGrupActionPerformed
    public void actualitzarMostrar() {
        IDGrup.setText(Integer.toString(llista_Grups.get(contadorGrups).getID()));
        nomGr.setText(llista_Grups.get(contadorGrups).getNom());
        numAlumnes.setText(Integer.toString(llista_Grups.get(contadorGrups).getnumAlumnes()));
        quotaGrup.setText(Float.toString(llista_Grups.get(contadorGrups).getQuota()));
        
    }
    private void esborrarGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esborrarGrupActionPerformed
        try {
            int opcio = confirmarOperacio();
            if (opcio == 0){
                if (llista_Grups.size() == 1) {
                JOptionPane.showMessageDialog(null, "No es pot esborrar quan només queda un grup",
                        "Esborrar", JOptionPane.ERROR_MESSAGE);
            } else {
                GrupEntity esborrar = llista_Grups.get(contadorGrups);
                grupTab.Delete(esborrar);
                JOptionPane.showMessageDialog(null, "Grup esborrat",
                        "Esborrar", JOptionPane.INFORMATION_MESSAGE);
                llista_Grups.remove(contadorGrups);
                contadorGrups = 0;
                actualitzarMostrar();
            }
            } else if(opcio == 1){
                JOptionPane.showMessageDialog(null, "Operació cancelada",
                "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (NullConnectionException ex) {
            Logger.getLogger(VentanaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_esborrarGrupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            grupTab = new GrupTable();
            BDConnection bdCon = new BDConnection(URL, PORT, BD_NAME, USER, PWD);
            grupTab.setConnection(bdCon);
            llista_Grups = grupTab.GetAll();
            actualitzarMostrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullConnectionException ex) {
            Logger.getLogger(VentanaAlumnes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AlumnesGrup alumGrup = new AlumnesGrup();
        alumGrup.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGrups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDGrup;
    private javax.swing.JButton afegirGrup;
    private javax.swing.JButton botoAnterior;
    private javax.swing.JButton botoObrirAlumnes;
    private javax.swing.JButton botoSeguent;
    private javax.swing.JButton esborrarGrup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton modificarGrup;
    private javax.swing.JLabel nomGr;
    private javax.swing.JLabel numAlumnes;
    private javax.swing.JLabel quotaGrup;
    // End of variables declaration//GEN-END:variables
}
